version: '3.4'
services:
  SweetDreams:
    image: sweetdreams
    container_name: SweetDreams_App
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: mvn spring-boot:run




