version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-browsers

    steps:
      - checkout
      - run : mvn clean package
      - store_artifacts:
          path:  target
      - store_test_results:
          path: target
      # - run: echo "$DOCKER_PASSWORD"| docker login -u="${DOCKER_USERNAME}" --password-stdin &&\
      #        docker-compose build &&\
      #        docker tag sweetdreams:latest meneghello/sweetdreams:latest &&\
      #        docker push meneghello/sweetdreams:latest
             